### ISSUE TITLE
Unable to initialise lirc 

### ISSUE THREAD

**Issue by mosesmc52** [tompreston/python-lirc#11]
Hi, 

I installed lirc on raspberry pie using the instructions from the readme page. lirc is not initializing. I get this error. Would you have any idea why this would be occurring?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lirc.pyx", line 122, in lirc.init (lirc/lirc.c:1286)
lirc.InitError: Unable to initialise lirc (socket was -1 from C library).

**Comment by michaelarnauts** [comment]
Check if lirc is running. You can try `irw` to see if you get events there.

**Comment by nolton** [comment]
Hola, yo tengo el mismo problema. cuando pruebo con irw este funciona correctamente.

**Comment by cadavre** [comment]
@nolton haven't you notices everyone here writes in ENGLISH, dude? <_<

**Comment by nolton** [comment]
@cadavre Lamento que debas esforzarte un poco más para leer lo que escribo, Amigo.

**Comment by lgcproductions** [comment]
Got the same issue as well. :(

**Comment by tompreston** [comment]
Try calling with verbose=True, like this:

    lirc.init('myprog', verbose=True)

Also, can you show me the code where you call `lirc.init()` and your `lirc` config files: `~/.config/lircrc` and `/etc/lirc/lircrc`

**Comment by tompreston** [comment]
Since there's been no update from the issue creator I'm going to close this.

See also #28 (comment)
