### ISSUE TITLE
Packaging issue in Pip

### ISSUE THREAD

**Issue by partofthething** [tompreston/python-lirc#12]
Hi. I have been tracking down [a bug in another project](https://github.com/home-assistant/home-assistant/issues/2306#issuecomment-231567612) where unexpected blocking was experienced and I think I isolated it to a packaging issue in the pip page. The tarball associated with [this package's pip page](https://pypi.python.org/pypi/python-lirc/) contains `lirc.c` which was compiled by Cython 0.15.1 on Thu Jul  4 13:50:19 2013. I think that file is out of date. A better way to package this would be to put `lirc.pyx` in the tarball and let the user's system perform the cythoning and building of the library.

**Comment by partofthething** [comment]
After re-studying the [cython compilation](http://docs.cython.org/src/reference/compilation.html) page, it looks like you have it packaged as recommended (with the `.c` file pre-cythoned). I just think it's possible that the `lirc.c` file that's uploaded under version `1.2.1` might need an update because it seems to still have the hang bug (#2) in python3. Maybe you just need to run:

```
make clean
make py3
python3 setup.py sdist
```
and re-upload.

**Comment by tompreston** [comment]
Done, [version 1.2.3](https://pypi.python.org/pypi?:action=display&name=python-lirc&version=1.2.3). Can you try that now please?

Sorry it's taken so long - I've been very busy lately.
