### ISSUE TITLE
RFE: Send  support

### ISSUE THREAD

**Issue by leamas** [tompreston/python-lirc#15]
Hi!

As of 0.9.2+, lirc supports sending data as described in http://lirc.org/html/lirc_client.html. This is basically a humble request that you add support also for sending into this library

**Comment by psyc0** [comment]
would also like to see this feature as im just blasting from python, ie mqtt -> python -> lirc, dont like doing os.calls :)

**Comment by tompreston** [comment]
I'm going to archive this repo, so I won't be adding this feature. See also #28
