### ISSUE TITLE
setup.py - cythonize call missing?

### ISSUE THREAD

**Issue by jpstotz** [tompreston/python-lirc#16]
Hi,

I was just trying to install your python-lirc package directly from the source provided here on Github. 
When I executed `setup.py` it tried to access `lirc/lirc.c` - a file that has to be generated using cython first, if I understand it correctly.

Therefore I assume that some call to `cythonize` is missing in setup.py, right? Or is it common that you have to to this manually, before executing `setup.py`?

**Comment by tompreston** [comment]
See https://github.com/tompreston/python-lirc#building-and-installing
