### ISSUE TITLE
package python3-lirc_1.2.1-1_armhf.deb essentially empty

### ISSUE THREAD

**Issue by iburadempa** [tompreston/python-lirc#18]
it only contains files below /usr/share/doc; accordingly, the size of the package is relatively small

**Comment by tompreston** [comment]
Does the install work using pip? I think the Debian packages have been removed.

**Comment by iburadempa** [comment]
Yes, thanks, installation with pip (and at least 'import lirc') works. A few months ago compiling from source also worked. May I suggest an update of README.md?
