### ISSUE TITLE
Does not work for Python3 on rpi Stretch

### ISSUE THREAD

**Issue by beetlegigg** [tompreston/python-lirc#19]
trying to install on rpi for python3 with Stretch.

With sudo apt-get install python3-lirc
I get:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-lirc

So I try to download the release files and install.  
Python2.7 install worked OK.

But version python3-lirc_1.2.1-1 appeared to install with error messages but in use I cannot import lirc -  ImportError: No module named 'lirc'.   I note the file size is minuscule so as per previous issue the file appears to be missing the necessary.

I tried to install python3-lirc_1.2.0-1 but I get:
dpkg: warning: downgrading python3-lirc from 1.2.1-1 to 1.2.0-1
(Reading database ... 128412 files and directories currently installed.)
Preparing to unpack python3-lirc_1.2.0-1_armhf.deb ...
Unpacking python3-lirc (1.2.0-1) over (1.2.1-1) ...
dpkg: dependency problems prevent configuration of python3-lirc:
 python3-lirc depends on python3 (<< 3.3); however:
  Version of python3 on system is 3.5.3-1.
dpkg: error processing package python3-lirc (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python3-lirc

**Comment by wallysalami** [comment]
Same problem here. Any progress?

**Comment by tompreston** [comment]
Does the install work using pip? I think the Debian packages have been removed.

**Comment by wallysalami** [comment]
I was getting a compilation error with pip, but I've just found out that I needed to run `sudo apt-get install liblircclient-dev` before `pip3 install python-lirc`. Thanks!

**Comment by beetlegigg** [comment]
Thanks wallysalami  and tompreston I also got the library to install without errors with the above instructions.   I will close the issue.
