### ISSUE TITLE
Specify lircd socket

### ISSUE THREAD

**Issue by michaelarnauts** [tompreston/python-lirc#24]
It seems there is no way to specify the lirc socket to use. In my case (on OSMC on a rpi), there are two lirc sockets:

* `/var/run/lirc/lircd`: uses kernel mapping, irw shows all buttons presses are using the remote `linux-input-layer`
* `/var/run/lirc/lircd-lirc0`: uses a normal lirc client, irw shows the correct remote

This python scripts seems to use `/var/run/lirc/lircd`, but I can't find a way to change this. Can this be specified somewhere?

**Comment by michaelarnauts** [comment]
I've also tried the `LIRC_SOCKET_PATH` env variable, but that doesn't seem to be used.

**Comment by tompreston** [comment]
I think that's an LIRC config, not a client. Have you considered using the in-kernel IR handling? https://github.com/tompreston/python-lirc/issues/28#issuecomment-712454662

Closing this since I'm archivng the repo.
