### ISSUE TITLE
Does not work for Python3 on RPI Buster

### ISSUE THREAD

**Issue by Walmtech** [tompreston/python-lirc#26]
Got lirc working on buster following these instructions https://www.raspberrypi.org/forums/viewtopic.php?t=235256

system info:
  Distro......: Raspbian GNU/Linux 10 (buster)
  Kernel......: Linux 4.19.57-v7+

So all lirc tools now working ok but this isn't included in buster and pip3 install with : pip3 install python-lirc results in failure probably down to the changes in LIRC10 

Complete output from command
```
/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kmzw_0xg/python-lirc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-72i824mv --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'lirc' extension
  creating build
  creating build/temp.linux-armv7l-3.7
  creating build/temp.linux-armv7l-3.7/lirc
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/lirc/ -I/usr/include/python3.7m -c lirc/lirc.c -o build/temp.linux-armv7l-3.7/lirc/lirc.o
  lirc/lirc.c: In function ‘__Pyx__ExceptionSave’:
  lirc/lirc.c:5050:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
       *type = tstate->exc_type;
                       ^~~~~~~~
```
Plus lots more of the same error

**Comment by tompreston** [comment]
What changes are required for `python-lirc`? Maybe submit a PR?

**Comment by Walmtech** [comment]
Thanks Tom - I'm still investigating but after somemore checking I don't think it is a problem with python-lirc as such.

**Comment by Walmtech** [comment]
Error was Unable to pip3 install python-lirc with Python 3.7: error: no member named 'exc_type' in 'struct _ts'.  Fixed by 

`git clone https://github.com/tompreston/python-lirc.git
find python-lirc -name '*.pyx' -exec cython {} \;
pip3 install python-lirc/`

I think this is a result of the package pulled in from PyPi having a precompiled *.c file ?
