### ISSUE TITLE
Current package 1.2.1 doesn't support Python 3.4

### ISSUE THREAD

**Issue by SailingGreg** [tompreston/python-lirc#6]
The Jessie version of Raspbian has Python 3.4 installed and the packages have a dependency <=3.3.

**Comment by tompreston** [comment]
Hello!
I'm not ignoring you -- I'm just having a little trouble getting it to build on Jessie.

I'm hoping to get something by this afternoon.

**Comment by tompreston** [comment]
Okay, can you try the arm packages from the release page now?

https://github.com/tompreston/python-lirc/releases/tag/v1.2.1

I can't get them to sign for some reason. This is what I'm getting out:

    gpg: skipped "Thomas Preston <thomasmarkpreston@gmail.com>": No secret key
    gpg: dpkg-sign.yoW4drXI/python-lirc_1.2.1-1.dsc: clearsign failed: No secret key
    
    dpkg-buildpackage: error: failed to sign .dsc and .changes file

Until I can get this fixed, I auto-send them to the raspbian repo. I'll try and manually get them in though.

**Comment by SailingGreg** [comment]
Thomas, that as allowed pifacecad to install - downloaded and installed
both the *armhf.deb file - was unsure about the python3 file as it was only
around 2k in size but it installed and the code is running. Note - I found
that I could not disable the device tree as this stopped the touch working
on the 7" screen but this does not appear to be an issue under Jessie -
tail of the config file attached.


pi@raspberrypidev ~/tmp $ tail /boot/config.txt

# NOOBS Auto-generated Settings:
hdmi_force_hotplug=1
config_hdmi_boost=4
overscan_left=24
overscan_right=24
overscan_top=16
overscan_bottom=16
disable_overscan=0
dtparam=spi=on
pi@raspberrypidev ~/tmp $




pi@raspberrypidev ~/tmp $ sudo apt-get install python3-pifacecad
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  python3-pifacecad
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 495 kB of archives.
After this operation, 1,348 kB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian/ jessie/main python3-pifacecad
all 2.0.8-1 [495 kB]
Fetched 495 kB in 1s (410 kB/s)
Selecting previously unselected package python3-pifacecad.
(Reading database ... 117512 files and directories currently installed.)
Preparing to unpack .../python3-pifacecad_2.0.8-1_all.deb ...
Unpacking python3-pifacecad (2.0.8-1) ...
Processing triggers for systemd (215-17+deb8u2) ...
Setting up python3-pifacecad (2.0.8-1) ...
You need to configure lirc. For help, go to:

http://piface.github.io/pifacecad/lirc.html#setting-up-the-infrared-receiver
.
Please REBOOT before using PiFace Control and Display.
Processing triggers for systemd (215-17+deb8u2) ...
pi@raspberrypidev ~/tmp $

**Comment by tompreston** [comment]
Glad you got it working - this will solve the issue for a few other people too! Not sure about your display issue though. Good luck!
