### ISSUE TITLE
deinit()

### ISSUE THREAD

**Issue by cymplecy** [tompreston/python-lirc#9]
Hi Tom
I was using original python lirc module but switched to yours as I needed non-blocking behaviour :)
I was using  deinit() as last line in my code which now gives an error (which it didn't with original lirc module)
Do I still need it or is it a bug?

**Comment by cymplecy** [comment]
Justfor further inf I'm using Python 2
also I did this
>>> import pylirc
>>> dir(pylirc)
['__doc__', '__file__', '__name__', '__package__', 'blocking', 'exit', 'init', 'nextcode']

which implied that their was an exit method - so I tried that instead of deinit() and no error

But deinit seems to be in the source code but not exit()
very confused :(

**Comment by tompreston** [comment]
You're importing `pylirc`, not `lirc`.
